spring.application.name=parkinglot

spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:testdb           # Use jdbc:h2:file:./data/testdb for a file-based DB
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.platform=h2


spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update               # Options: none, update, create, create-drop


spring.h2.console.enabled=true
spring.h2.console.path=/h2-console                 # Access via browser at localhost:8080/h2-console